### ISSUE TITLE
0.4.7 doesn't work with Philips, 0.3.5 does

### ISSUE THREAD

**Issue by Chaos2000** [masmu/pulseaudio-dlna#143]
Hi Massimo,
many thanks for  pulseaudio-dlna.
I wanted to upgrade from version 0.3.5 which works fine with Philips MCi500H and MCi298 to 0.4.7 but 0.4.7 could not detect the MCi500H but detected MCi298 but could not start it (wake up). Afterwards I have to restart/reboot MCi298. Maybe you can have a look into this and find out the differences.
Many thanks.

**Comment by dermassen** [comment]
Hi Massimo,
same issue on my side with my Philips NP2500. 0.3.5 is the last version that detects this device.
Maybe you can find out what's going on.
Thanks a lot!

**Comment by masmu** [comment]
Could you create a full _debug.log_ and pastebin it here?
```bash
pulseaudio-dlna --debug 2>&1 | tee -a debug.log
```

**Comment by dermassen** [comment]
Here you can find the debug output of the current version (0.4.7) and from version 0.3.5 (which is working with my Philips Streamium NP2500).
Thanks for your help!
[debug_035_log.txt](https://github.com/masmu/pulseaudio-dlna/files/80222/debug_035_log.txt)
[debug_047_log.txt](https://github.com/masmu/pulseaudio-dlna/files/80224/debug_047_log.txt)

**Comment by masmu** [comment]
Thank you for your _debug.logs_. I found a problem with the regular expression getting the device id. That failed in _0.4.7_.

I fixed that issue, so please check it out to verify that it solves the problem.
To do that you can:

- Get a copy of the [branch](https://github.com/masmu/pulseaudio-dlna/tree/bug/philips-discovery) that contains that fix.
- Or locate the `renderers.py` and change lines 47 - 52 to the following:
```python
    def _retrieve_header_map(self, header):
        header = re.findall(r"(?P<name>.*?):(?P<value>.*?)\n", header)
        header = {
            k.strip().lower(): v.strip() for k, v in dict(header).items()
        }
        return header
```
On Ubuntu and debian the file should be found at `/usr/lib/python2.7/dist-packages/pulseaudio_dlna/renderers.py`. Note that you have to edit the file with root permission.

**Comment by dermassen** [comment]
Danke Massimo,

das schaue ich mir heute abend gleich mal an und melde mich dann wieder!

Grüße,
Martin

2016-01-07 14:08 GMT+01:00 Massimo Mund <notifications@github.com>:

**Comment by dermassen** [comment]
Hi,
I patched renderers.py - the error is now gone, but we still have the 'Binding socket to ""' problem and the device is still not discovered. See attached logfile.
Martin
[debug_047_log_new.txt](https://github.com/masmu/pulseaudio-dlna/files/81615/debug_047_log_new.txt)

**Comment by masmu** [comment]
Could you please try the --port flag and use another one? Like pulseaudio-dlna --port 12321

I cannot look right now, but for now this is worth a try.

**Comment by dermassen** [comment]
unfortunately, this does not change anything!
[debug_047_log_port12321.txt](https://github.com/masmu/pulseaudio-dlna/files/82257/debug_047_log_port12321.txt)

**Comment by masmu** [comment]
Could you please paste a copy of [http://192.168.1.3:8080/DeviceDescription.xml](http://192.168.1.3:8080/DeviceDescription.xml) here?

**Comment by masmu** [comment]
Please contact me via email. You will find my email within the donation link.

**Comment by typhoe** [comment]
Hi,

on Manjaro / Arch Linux, the renderers.py file is located in site-packages (not dist-packages):
sudo vim +47 /usr/lib/python2.7/site-packages/pulseaudio_dlna/renderers.py

And changing the function _retrieve_header_map like you suggested works for me.

My Phillips NP2900 that wasn't recognized in 0.4.7 is now detected and can receive (and play) the stream.

Thank you!

**Comment by masmu** [comment]
Thanks for the feedback. I consider that fix as working and it will be in the next release.

**Comment by typhoe** [comment]
Perfect! Thank you very much!

**Comment by masmu** [comment]
* __0.5.0__ - (_2016-03-09_)
    - Set Yamaha devices to the appropriate mode before playing (thanks to [hlchau](https://github.com/hlchau)) (new dependency: `python-lxml`)
    - Fixed a bug where some SSDP messages could not get parsed correctly
    - Also support media renderers identifying as `urn:schemas-upnp-org:device:MediaRenderer:2`
    - Added the `--disable-workarounds` flag
    - Added the `--auto-reconnect` flag
    - Added the `--encoder-backend` option (new optional dependencies `ffmpeg`, `libav-tools`)
    - Removed shared encoder processes
    - Increased the default HTTP timeout to 15 seconds
    - Fixed a bug where manually added renderers could appear twice
    - Added device state polling for devices which start playing on their own
    - Added the flac encoder for _Google Chromecast_
    - Added support for _Google Cast Groups_ (new dependency `python-zeroconf`)
    - Removed dependency `python-beautifulsoup`
    - Fixed a bug where bytes were not decoded properly to unicode
